# Discord bot token
token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# Bot prefix and status
prefix = ","
status = "xyzw"

# The ids of all users who will have acces to owner commands
owner_ids = [
    1234,
    1234,
    1234,
]

# The ids for your discord server and channel (Note: dnkl stands for do-not-kick-list)
guild_id = 859916798111907871
error_channel = 859916798111907875
dnkl_channel = 859916798111907875
ticket_channel = 859916798111907875
log_channel = 859916798111907875
registration_channel = 859916798111907875
staff_announcements_channel = 859916798111907875
partner_channel = 859916798111907875
qotd_thread_channel = 1424565934672183326
geoguessr_thread_channel = 1424565934672183326
milestones_channel = 859916798111907875
milestones_category = 859916798111907875
weekly_gexp_lb = 859916798111907875
daily_gexp_lb = 859916798111907875
rank_upgrade_channel = 859916798111907875
staff_bridge_channel = 859916798111907875

# The name of your Hypixel guild
guild_handle = "Miscellaneous"


# The requirements for joining the GvG team
gvg_bw_fkdr = 1.6
gvg_bw_wins = 500
gvg_sw_kdr = 1.2
gvg_sw_wins = 1000
gvg_duels_kills = 2000
gvg_duels_wlr = 1.5

# Names of allied guilds
allies = [
    "Betrayed",
    "Blight",
    "OUT",
    "Electus",
    "Lucid"
]

api_keys = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
]

# The names of discord ticket categories
[ticket_categories]
generic = "ðŸŽ« Ticket Section"
other = "OTHER"
report = "REPORTS"
milestone = "MILESTONES"
dnkl = "DNKL"
event = "EVENT"
registration = "REGISTRATION"
registrees = "REGISTREES"

# Example: Rank 1 is member, 2 is VIP, 3 is MVP, 4 is Helper, 5 is Admin
[ingame_ranks]
rank_1 = { name = "RANK 1", requirement = 50000, is_staff = false }
rank_2 = { name = "RANK 2", requirement = 200000, is_staff = false }
rank_3 = { name = "RANK 3", requirement = 400000, is_staff = false }
rank_4 = { name = "RANK 4", requirement = 50000, is_staff = true }
rank_5 = { name = "RANK 5", requirement = 50000, is_staff = true }


[discord_roles]
admin = 859925758801870848
staff = 859925758801870848
helper = 859925758801870848
former_staff = 859925758801870848
new_member = 859925758801870848
processing = 859925758801870848
guest = 859925758801870848
member = 859925758801870848
achievable_rank_0 = 859925758801870848
achievable_rank_1 = 859925758801870848
ally = 859925758801870848
booster = 859925758801870848
sponsor = 859925758801870848
gvg_team = 859925758801870848
giveaways = 859925758801870848
veteran = 859925758801870848
recruiter = 859925758801870848
qotd_ping = 923978802818871356
geoguessr = 1347488380161622036
